services:
  app_proxy:
    environment:
      APP_HOST: community-zoraxy_server_1
      APP_PORT: 8000
      PROXY_AUTH_ADD: "false"
  server:
    image: zoraxydocker/zoraxy:v3.1.6@sha256:37a00bb6538067771ee59212f0155c75b1a74fbeb06a50bc946e22be7e4726a1
    restart: on-failure
    ports:
      - 42080:80
      - 42443:443
    volumes:
      - ${APP_DATA_DIR}/config/:/opt/zoraxy/config/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      FASTGEOIP: "false"
      ZEROTIER: "true"
