services:
  app_proxy:
    environment:
      APP_HOST: community-zoraxy_server_1
      APP_PORT: 8000
      PROXY_AUTH_ADD: "false"
  server:
    image: zoraxydocker/zoraxy:3.2.5r2@sha256:164a5627756d048eef3195b982d5e73df0a6bf77a784171f1310e29780434f3b
    restart: on-failure
    ports:
      - 42080:80
      - 42443:443
    volumes:
      - ${APP_DATA_DIR}/config/:/opt/zoraxy/config/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      FASTGEOIP: "false"
      ZEROTIER: "true"
